### PR TITLE
Spike: Fix proposal call

### LINKED ISSUE #8: Test and confirm submitted extrinsic call is triggered correctly

### PR DESCRIPTION
**Pull request by aidan-starke**
## Summary

 - Use `api.createType` to create `Call` for proposal call
 - Closes #8
 - Fetch & display Proposal Call on proposal view page with skeleton loading effect

## Notes

 - We need the full list of extrinsics we want available so that we can make sure the arguments for the call are getting passed in correctly

## Preview
 - https://app-gov-git-spike-fix-proposal-call-cennznet.vercel.app/

### CODE REVIEW

**Review by ken-futureverse — CHANGES_REQUESTED** [review]
looks good, but I think we need a better way to display the Proposal Call

- No need to display `api.tx` as it might confuse readers who are not familiar with `api.js`
- Would be good to display the name of the parameters

File: apps/gov-website/pages/proposals/[pid].tsx [hunk 1]
```diff
@@ -15,98 +23,137 @@ import { useCENNZApi, useCENNZWallet } from "@app-gov/web/providers";
...
+	};
+};
+
+export const getStaticProps: GetStaticProps = async (content) => {
+	const api = await getApiInstance(CENNZ_NETWORK.ChainSlug);
+
+	const proposalId = content.params.pid as string;
+	const { proposal } = await fetchProposal(proposalId);
+	const proposalCall = await fetchProposalCall(api, proposalId);
+
```
Comment (ken-futureverse) [inline apps/gov-website/pages/proposals/[pid].tsx:57]: can return not found here so we can handle it globally using the custom 404 page

File: apps/gov-website/pages/proposals/[pid].tsx [hunk 2]
```diff
@@ -15,98 +23,137 @@ import { useCENNZApi, useCENNZWallet } from "@app-gov/web/providers";
...
-					</h2>
-					<p className="mb-8">
-						Lorem laborum dolor minim mollit eu reprehenderit culpa dolore
-						labore dolor mollit commodo do anim incididunt sunt id pariatur elit
-						tempor nostrud nulla eu proident ut id qui incididunt.
-					</p>
-					<div className="mb-12 min-w-0">
-						<WalletSelect required />
-					</div>
+				<If condition={router?.isFallback}>
```
Comment (ken-futureverse) [inline apps/gov-website/pages/proposals/[pid].tsx]: we won't need this if we use 404 page

File: libs/web/utils/src/fetchProposal.ts [hunk 3]
```diff
@@ -1,13 +1,20 @@
-export const fetchProposal = async (proposalId: string) => {
-	const response = await fetch(`/api/proposals/${proposalId}`);
+import type { ProposalInterface } from "@app-gov/node/types";
+import { BASE_URL } from "@app-gov/service/constants";
 
-	const data = await response.json();
+export const fetchProposal = async (proposalId: string) => {
+	try {
+		const response = await fetch(`${BASE_URL}/api/proposals/${proposalId}`);
```
Comment (ken-futureverse) [inline libs/web/utils/src/fetchProposal.ts]: don't need `BASE_URL` here, you can just do `/api/proposals`

File: libs/service/constants/src/index.ts [hunk 4]
```diff
@@ -46,3 +46,6 @@ export const PINATA_JWT: string = process.env.NX_PINATA_JWT ?? "";
 export const PINATA_GATEWAY: string = process.env.NX_PINATA_GATEWAY ?? "";
 
 export const MONGODB_SERVER: string = process.env.MONGODB_SERVER ?? "";
+
+export const BASE_URL: string =
```
Comment (ken-futureverse) [inline libs/service/constants/src/index.ts]: don't need to define `BASE_URL`

**Review by ken-futureverse — CHANGES_REQUESTED** [review]

**Review by ken-futureverse — DISMISSED** [review]

**Review by ken-futureverse — APPROVED** [review]
